name: Docker Nginx Lab
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  docker:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Image
      - name: Build Docker image
        run: docker build -t mynginx:test .

      # Test Image
      - name: Test Docker image
        run: |
          docker run -d -p 8080:80 --name test-nginx mynginx:test
          sleep 5
          curl http://localhost:8080 | grep "Hello from GitHub Actions"

      # Health Check
      - name: Health Check
        run: |
          curl -f http://localhost:8080 || exit 1

      # Stop and Remove Test Container
      - name: Clean up Test Container
        run: docker stop test-nginx && docker rm test-nginx

      # Tag Version
      - name: Tag Version
        run: |
          docker tag mynginx:test ${{ secrets.DOCKER_USERNAME }}/mynginx:latest
          docker tag mynginx:test ${{ secrets.DOCKER_USERNAME }}/mynginx:${{ github.sha }}

      # Push Image
      - name: Push to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mynginx:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mynginx:${{ github.sha }}
